// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zajsujrzfuuyjbmdabca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphanN1anJ6ZnV1eWpibWRhYmNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMDIzNjgsImV4cCI6MjA2MDY3ODM2OH0.g_bUvQV-HKqtO49ZQnjgvNy0Ar2CdTw6zknFA3esF0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);